using System;

namespace FFXIV_GameSense
{
	[Serializable]
	public enum ChatChannel : byte
	{
		None,
		Debug,
		UrgentInformation,
		GeneralInformation,
		Say = 10,
		Shout,
		Tell,
		Tell_Receive,
		Party,
		Alliance,
		Linkshell1,
		Linkshell2,
		Linkshell3,
		Linkshell4,
		Linkshell5,
		Linkshell6,
		Linkshell7,
		Linkshell8,
		FreeCompany,
		NoviceNetwork = 27,
		CustomEmotes,
		StandardEmotes,
		Yell,
		Party2 = 32,
		PvP = 36,
		CWLS1,
		Damage = 41,
		FailedAttacks,
		Actions,
		Items,
		HealingMagic,
		BeneficialMagic,
		DetrimentalEffects,
		Echo = 56,
		SystemMessages,
		SystemErrorMessages,
		BattleSystemMessages,
		GatheringSystemMessages,
		NPCSay,
		LootNotices,
		CharacterProgress = 64,
		LootMessages,
		CraftingMessages,
		GatheringMessages,
		NPCAnnouncements,
		FCAnnouncements,
		FCLoginMessages,
		RetainerSaleReports,
		PFRecruitmentNoficiation,
		SignSettings,
		DiceRolls,
		NoviceNetworkNotifications,
		CWLS2 = 101,
		CWLS3,
		CWLS4,
		CWLS5,
		CWLS6,
		CWLS7,
		CWLS8
	}
}
